### ISSUE TITLE
Desiable the Notification of unread messages 

### ISSUE THREAD

**Issue by milts10** [Wolox/react-chat-widget#240]
There is a notification of unread messages that I want to completely get rid of (or change the number by hand to whatever I want to)
![image](https://user-images.githubusercontent.com/15010565/106798170-e54db980-665d-11eb-9952-ca269eb7654c.png)

Is anyone know how to do that?

**Comment by jotahws** [comment]
You can simply modify your CSS to hide the badge:

```css
.rcw-launcher .rcw-badge {
    display: none;
}
```
